### ISSUE TITLE
GH Pages app

### ISSUE THREAD

**Issue by elliottkember** [wokwi/fastled-monaco#1]
I found [an article](https://codewithhugo.com/build-and-deploy-a-vue/react/vanilla-js-app-with-parcel-and-github-pages/) about deploying Parcel to GitHub Pages. Might be a great idea for hosting a demo!

**Comment by elliottkember** [comment]
Looks like all that's needed is

```
{
  "scripts": {
    "start": "parcel index.html",
    "predeploy": "rm -rf dist && parcel build index.html --public-url YOUR_REPO_NAME",
    "deploy": "gh-pages -d dist"
  },
  "devDependencies": {
    "gh-pages": "^1.2.0",
    "parcel": "^1.9.7"
  }
}
```

**Comment by urish** [comment]
We now deploy the demo to vercel, automatically!

https://fastled-monaco.vercel.app/
